os: linux
language: java
services:
  - docker
cache: 
  directories:
    - $HOME/.m2
dist: focal
install: skip

stages:
  - name: test

jobs:
  include:
    - stage: test
      name: testing
      script: true

after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
