os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip

stages:
  - name: test
  - name: deploy

jobs:
  include:
    - stage: test
      name: testing
      script: true

    - stage: deploy
      name: deploy
      script: echo "Deploying..."

after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
